package utilities;

public class ASCII {

    public static String tomCruise() {
        return ":-.``````````````````````..............--------------::------:-::::::::-------:-::::----------------------:::::::::::::::::::::::::::///://///////////:::::::::////////////////////////////:::::::::::::\n" +
                "+:..``````````````````````.................----------------------------------------------------------------:-::::::::::::::::::::::::::::::://///////::::::::::://///////////////////////:::::::::::::::\n" +
                "o/-.`````````````````````````````.................-------------------------------------------------------------:-:::--::::::::::::::::::::::/:::/::::::::::::::////////////////////:://:::::::::::::::::\n" +
                "ho/-.`````````````.........`````````....................--.....--.........................------.....--------------------::::-----:-:::::::::::::::::::::::::::::::::://////////::::::::::::::::::::::::\n" +
                "dho/-.````````````ossyysss-`````````:yysssyyo`.........+yyo..-syy........................yyssssyy......----:yysssyy/---------.syo-::yy::::::::::-yy+:::::::::-sysoosyy-:/:::::::/yysssss-::::::::::::-:-\n" +
                "ydho/-.`````````````-yy+````````````:yy:..sys``````````+yyy+-syyy.......................-yy/............--.:yy:-:yy/---------.sys--:yy::::::::::-yy+:::::::::-oyy+///:-:::::::::/yy+///-::::::::--------\n" +
                "oydho/-.````````````.yy+````````````/yy:``sys``````````+yysysysyy.```````..`............-yy/.......--------:yy/syyo:---------.sys.-:yy/:::::::::-yy+-::::::::-:/++osys-::::::::-/yy+///.-::::::---------\n" +
                "+shdyo/-.```````````-yy+````````````/yysssyys`````````.+yy:syo/yy-`````````.`...........-yysssyyy----------/yy::sys:----------syysssyy/----------yy+-::::::::-syyooyyy-::::::::-/yysssss----------------\n" +
                "/oydhs+:-.``````````.--.````````````.-------.``````````---.....--.`````````..............---::::------------::---:::----------::::::::-----------:::----------:::::::::::::::---::::::::----------------\n" +
                ":+sdhso+:-.`````````````````````````````````````````````````````````````````....................--------------------------------------------------------------------------------------------------------\n" +
                ":/shdyo+/:-.`````````````````````````````````````````````````````````````````..........:..........------------------------------------------------------------------------------------------------------\n" +
                ":/shhso++/:-.````````````````````````````````````````````````````````````````...-://ooys+yyhhyo:---:-.-:-----------------------------------------------------------------------------------------:---:::\n" +
                ":/shhso+///:-.```````````````````````````````````````````````````````-`...---:-:sydddhmmmNNNNNNmddyysssso+//:-----------------------------------------------------------------------------::::::::::::::\n" +
                ":+sdhs+/////:-.`````````````````````````````````````````````````````/o:.+ossydddddmmmmmmmNNNMMMNNNNNNmddy+::-.------------------------------------------------------------------------::::::::::::::::::\n" +
                "/oydhs+/::://:-.````````````````````````````````````````````````..:.ody-+dNNNNMMMMMMNNNNNNMMMMMMMMMNNNNNmdhs/:------------------------------------------------------------------:::::::::::::///////////\n" +
                "/ohmdyo+/::://:-.```````````````````````````````````````````````-::+dmNddmNNmNMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNhh+-.------------------------------------------------------::::::::::::::::::://////////////\n" +
                ":+sdmdho+::::::-.```````````````````````````````````````````````.osshNMMMMNMMMMMMNNNMMMMMMMMMMMMMMMMMMMMMNMNNNd+---------------------------------------------------::::::::::::::::::://////////////////\n" +
                "-:+ydmmhs+/:::::-.```````````````````````````````````````````````-symNMMMMMNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNy/------------------------------------------::::::::::::::::::::::::////////////////////\n" +
                ".-:+sdmmdyo/:::::-.```````````````````````````````````````````````:odNNNNNNNNNNNNNNNNMMNNMMMNMMMMMMMMMMMMMMMNNNNNh/-------------------------------------:-::::::::::::::::::::::::::::://///////////////\n" +
                "..-:/ohmmmhs+/:::-..``````````````````````````````````````````````-ohddhdmdddmmddmmmNNNNNNNNNNNNNNNMMMMMMMMMMMNNNNmy/--------------------------::-:::::::::::::::::::::::::::::::::::://////////////////\n" +
                "...-:+sdmmmds+/:::-.``````````````````````````````````````````````:yhs//ososyyhyssssyhdddmmmmmNNNNNNNNNNNMMMMMMMNNNNho:-------------------:-:::-::::::::::::::::::::::::::::::::::://///////////////////\n" +
                "....-:ohmmmmdy+/:::-.````````````````````````````````````````````.-yy--/s+oosoossoooossyyyyyyhdmmNNNNNNNNNNNNMMMMNNds::--------------:::::::::::::::::::::::::::::::::::/:/:::://///////////////////////\n" +
                "....-:+sdmmmmds+/::--.````````````````````````````````````````````.s:-:/oo+oooooooooooossssyyyhdmmNNNNNNNNNNNMMMMNNo::--------------:-::::::::::::::::::::::::::::::::::::::////////////////////////////\n" +
                "....-:/+shdNmmds+/::-..```````````````````````````````````````````./.-://++++o++++oooooossssyyhdmmNNNNNNNNNNNMMMMNNd:-------------------::::::::::::::::::::::::::::::::::::::://///////////////////////\n" +
                "-...-::/+oymNmmhs+/::-..``````````````````````````````````````````-:.-:://++++++++oooooosssssyyhdmNNNNNNNNNNNNMMMNNd/-----------------------::::::::::::::::::::::::::::::::::::::::////////////////////\n" +
                "--..--:::/ohmNmmho+/:--.```````````````````````````````````````````.-://++++++++ooooooooossssssyhdmNNNNNNNNNNNNNNNNo----------------------------:::::::::::::::::-::::::::::::::::::::::////////////////\n" +
                "//:::::-::+sdNNmmho/::-..```````````````````````````````````````..::://+ooooooooosysssssyyssssssssydNNNNNNNNNNNNNNm:--------------------------------------------------------:-::::::::::::::::://///////\n" +
                "yysssooo+osydNNNmmyo/::-..`````````````````````````````````````-:/dmmmmdhhyshdmmNNNNNNNNmdhhyssssssydmmmdddmmNmmNNm----------------------------------------------------------------:::::::::::::::://///\n" +
                "mdysooooosyhmmNNNmdyo/::-.````````````````````````````````````.//+ymNNNNNmyshNNNNMMMMMNNNNNshyssooosyddNNNNmhyyyydh.--------------------------------------------------------:-:-:----:::-::::::::::::://\n" +
                "ys+/:::--:/+oydmNNmds+/:--.```````````````````````````````````.:///dNNNNNy/+smNNNNMMMMNNNNNmysssssssymNNmdhyhhyhhy+------------------------------------------------------------:------------::::::::::::\n" +
                "yyso++/--.--:/shmmmmds+/:-..```````````````````````````````````.///hmNNNd//oshmNNNNNNNNNNNNNhysssooooyddhhhhysosyy----------------------------------------------------------------------------::::::::::\n" +
                "+++///:--...-:/sdmmmmhs+/:-..```````````````````````````````````./+hmNNd+/+osyhdNNNNMNNNNNNNyssssssssosssyhddhsoyo.--------------------------------------------------------------------------:::::::::::\n" +
                "--------.....-/ohmNNmmhs+/:-....`.`.`.`.`````````````````````````./hmmh//++osyyhhdmNNNNNNNNhyssssssssssssshyyyyss-...---------------------------------------------------------------------------::::::::\n" +
                "----........-:/ohmNNNmmho+/:-...................``````````````````./oo+/ossssssyhyyhhddmddyyyyyyyyssssssyyssosss+......-----------------------------------------....--------------------------------::::\n" +
                "--------.--.-/+shhdNNNmdyo+:--....................`.```````````````:/++oyhdmmdhhhyyyyssyyyyyyyyyyyysssyyyyysoosy-................------..-------------------...........----------------------:------:-::\n" +
                "-----------:/osssyymNNNmdso/:--.......................`````````````-//+++sddddhhysssssysyyyyyyyyyssssyyyyyyysymh.......................-..--..-..------------..........---------------------------:---:-\n" +
                "---------:/+oyhyyhhmNNmmmhs+/:-.........................`.``.`.`....:/+//+yyyyyyssoosssssyyyyyyyyyysssyyhhhyshh+.................................-.---------...........-------------------------------:-\n" +
                "--------:+oyyssoshmNmNmmmmho+/:-...................................://///osyhyyyssysssssyyyyyyyyyyyysyssyyyyy+-.....................................-.-.................--------------------------------\n" +
                "-------:/oyds+///+shmmNNmmdyo+/--..............................--:/so/+shhhdddddddddhyyyyyyyhhyyyyyyyysyyyyyssy+-....................................................-.-.-------------------------------\n" +
                "--------:/++/::--:/+shmmNmmdyo+:-...........................-ossossyyooyooyhhhhhhhhhhhhyyhhhhhhhyyyyhyhyyyyyshNNmy:...................................................----------------------------------\n" +
                "-------------------:/oymmmmmdyo/-...........................ssyyyyyyhhsssydddddddddhhhhhhhhhhhhhhhhhdhhhhyyyydNNNNdo-............................................-.-------------------------------------\n" +
                "-..-.---------------:/ohmmmmmds+:-..........................hoydmddhhhhyoossyyyhhyhyhhhhhhhhhhdddddddhhhhyyyydNNmNNmy-...........................................---------------------------------------\n" +
                ".............-.------:+sdmmmmmyo/-..``......................shhmhhdddmmds+oossssssyyyyyyhhhdddmmmmdhhhhhhyyyydNNmNNNmdsoo/:.....................................----------------------------------------\n" +
                "...............------:/odmmmmmds+:-..```.....................yhdhyddmmmdhssyhhhhhhhhhhhdddddmmmmddhyyyhyyyyyydmNNmNNmNhsssso:-................................-------------------------------------:-:::\n" +
                "------.....----------:/oymmmmmmhs/:..`..```..................:hhdyhdddmmddddmmmmmmmmmmmmmmmmmmmddhhyyyyyyyyyhdmNNmNNNNdsssssys+-...............................--------------------------------:------::\n" +
                "----------------------:/oydmmmmmho/-....`.`.`...`....`.......-yhhdhddmNNmmNNNmmNNNNNNNNNNNNmmmddhhyyyyyyyyhhhdNNNmNNNmddyssssyssoo+osssoo++///:-...............-----------------------------------------\n" +
                "----------::::---------:/+sdmmmmdy+:-......`.`.``....-::/+/++ohddddmmmNNNNNNNNddmNNNNNNNNNNNmmdhhyyyyyyyyhhddmNNmNNmNmmNdhhhysyysyhdmmmmdhyysso++/-.................------------------------------------\n" +
                "---------:::::::--:-----:/+ymmmmmds/:........--::///+++++oooosymmdddmNNNMMNNNNNmmmmNNNNNNNmmmmddhhyyyyyyyhddmNNNmNNmmmNmdhyyyhhhhh++sdNNNNNmmdhysoo+/--................-....----------------------------\n" +
                "-----::::::::::::::::::--:/ohmmmmmho/-.-//+o+++++ooooooooossyshmNmdmhdmNNMMNNNNNNmmmmNNNNNNmmmmddhhhhhyyhhdmmNNNNNmmmNNddddhyyyyddy++syyhdmNNNmmmddhyo+/:-..................---------------------------:\n" +
                "----::::::::///:::::::::::/oymmmmmmy++osyyssoossssssssssyyyyyydmmNhdyyhdmNMMNNNMNNmmmmmmNNNNNmmmddddhhhhhdmmNNNNNmmmNNddhhhhhhysyyyo+osssyyddddhhhyoo+++oo+/:...........----------------------------::::\n" +
                "::::::::::::////::::::::::/+sdmNmmmdyhddhssosoyhyyyysyyyyhyhhdmmmNhhoddmmNNNMNNNNNNmmmmmmmNNNNmmmddddhhddmmNNNNmmmNMNNmdhhhhhhhyyyhsosysyyyyyhhdmmmdhs+/::/:-............---------------------------::::\n" +
                ":::::::::::::///:::::::::::+ohmmmNmdddhsooysyyyddhhhhyyyhhydhdmmmNdhodddmmNNNNNNNNNNNmddddmmNNNmmmmdddddmmmNNNmmNMMMNmdddhyyyyyyyhhsohyyyysyhhyhdmmmmmdhs+/-...........------------------------:::::::::\n" +
                ":::::::::::::////::::::::::/+oydNmddyso/++osyhyhdddhhhhhhhhmhdmmmmmhsdmhhhmmNNNNNmmNNNmddhddmNNNNmmmdddmmmmNNNNMMMMNNmmdyyhhyyyhhddssdhhhyydhyhhhdddmmmmdy++.---...-------------------------::::::::::::\n" +
                "::::::::::::::///:::::::::-::/oymdy+//++/+oshdyhhmmdhhhhhddmdmNNNmmNhhNmhhhdNNNNMNNNNNNmddhhdmmNNmmdddmmmmmmMMMMMMNNmmmdhyyyyyyhhddsydhhhhddhhhhhhhddddddyoo:-----------------------------::::::::::::::\n" +
                ":::::::::::::::::::-:-------::+sds:/+/+s+ooyhdhhhdmmddddmmmmNmNmmmmNmyNNhhhhmmmNNMMNNmNNNdhhhdmmmmmdddmmmddNMMNNMNmmmmmdhhhyyyyhhddshddhhdmdhhhhhhhhhdddhyy+/-::::::::::::-------------:::::::::::::::::\n" +
                "::::::::::----:::::----------:/os:/::/o+:oyhhhdhhhdmdddddddmNdNmmmNNmddNmNmmmmmmNMMMNNmNNNdhhhddddddhdmmmmNMNNNNNNNmmdhhhhyyyyyyhmdhmmdddmddddddhhhhdddmhyy+s:::///////::::::::::-:::::::::://///////:::\n" +
                "::::::--------:::::-----------:/::::/o+++shmdhhhhhhdmdddddddmdNmmmNNmmhmmdmmmNNmmNMMNNNmNNNdhhhhhhhhhdmmmNMNNNNNNmmmmmdhysssyssydmdmNmdddmdmdmdddhddddmmyyysy+://////////::::::::-:::::::::://///////:::\n" +
                "---------------::::-------------/://+//+ohmmmdhyhhhdmddddddmmmNdmmNNmmNNNNNNNNMMNmNMNNNNMNdmdhyyysyyydmmNNNNNNNNmmddddhhhysssssymmddNNdddmddddddddmhdmmdhyyoso/:////////:::::::-------::::::::::::::::::\n" +
                "----------------::::---------:/-/+o//::oyhmmmmdhyhddddmddddmdmmdmmNNmmNMNNMMMMMMMNNNNNNNNNhhmdysyssshdmNNNNNNNNNmddddhhhyyysosshmdhdmNmdddmddddddhhdmNdNNyyyyo+:://///:::::-------------------::::::::::\n" +
                "----------------::::--------:o::+/////shhddmmmmmdhhdddmmdmdmdmdmNmNNmmmMNNNNMMMNNNMMNmmmNNNmddhsssohmmNNmmmmmmNmdddhhyyyyyyyosyNNNNmmNmddmdmddddhhdmNdmNmdyhsy+/::::::::----------------------------::::\n" +
                "------------:::://///::::::/o+//++/oshhhyhhddddddhhhhhdddddddhhddmNNmmdmmdddmNNNNNmmdddmmmmNNNdo:/+mmNNmdddhhdmmhhdhyyyysssyssymNNmmmddddmmmhhhhhhddhddmdhyyoos+::::::::::::::::::::::::::::------------\n" +
                "------------/++......`````````````````````````` ````````` ``     +mmdo.    `/dNNmy        `/dNNm++hNmms-    `-ymdmm.   ohyyy    hm+   `ymmmh                                             .++:-...-------\n" +
                "------------:/os:...``````.``.```````````````` `     `` `      ``+d/`  ````   :hNh    ````   :hNdymN+.  ````   -sdm.   shhyy    hm/    `hmNh                                            :s+:-.........--\n" +
                "-.------------:+soososossssssyyyssssssssssyssyyyyyyyyyyys     shhds   .ddhd/   :my   `dddd+   -NNhmm    hddds   `dd.   shhhh    hm/     -mNh    yyyyyyysssssyysssossooooooooooooooooooooo/--............\n" +
                "---::::::::----:/+syyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhNm     hNNNs   .NNhh/   :my   `mdhdo   -NNNNm    dmmNy   .dd.   sdhhh    hd/      /mh    mdyyyyyyyyyyyyyyysyyyssssssssssssssssyo/:--......--.----\n" +
                "//++++++++//:----:+yhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyssyyhmm     hNNNs   .NNmy/   :dy   `dddmo   -NNNNm    dmmmmmmmmNN.   yNNNm    hd/       oh    mmsssssssssssssssssssssssssssssssssyyo/:----------------\n" +
                "yyyhhyssyyyo/:----:+sdddddhhdhddddddddddddddddddddddddmmm     hNNms   .Nmmy:   :my    ////-   /NNMNm    dmy+++++oNN.   yNNNd    hm+   :.   o   `mmdddddddddddddddddddhhhhhhhhhhhhhhs+:------------------\n" +
                "mmmmmmmmmdhs+:----:+yyhdyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhNm     hNmms   .mmmd/   :my         `/hNmNNNm    mNo     `NN.   smNNm    hm+   /d`      `Nmyyyyyyyyyyyyyyyyyyyyssssssssysyy+/:-------------------\n" +
                "NNNNNNNNNmdyo/:--:+hyyhyhhyyyyyyyyyyyyyyyyyyyyyyyyyyyyhNm     hNmms   .Ndhm/   :Ny   `++++omNNNmNNNm    dmho/   `mm.   smNNm    hm+   /Ny       mdsssssssyssssssssssssssssssyyyhs+:---------------------\n" +
                "NNNmmNNNNmmdso+/:/ossooysyhdddddddmddddddmmmddddddddddmNm`    hNmms   .Nmdm/   /Nh   `mmNNNNNmNNmNNm    dmmNy   `mm.   smNNm  ``hd/   /NN+      mmddddddddddddmmmdhdddddhhhhhhyo/:----------------------\n" +
                "dddhhddmmmmmdhyo++o+/:/:ooydhhyyyyyyyyyyyyyyyyyyyyyyyyhmm`    hNNNh.   ....`  .smh````mmmNNMNNmNNNNm-   ----.  `/dd/   .----```:dd+`  /NNN:     mdyyyyyyyyyyyyyhhyyhyyyyyyyyho+:------------------------\n" +
                "hhyyyyhddmmmmmmooossososyyydmmhyyyyyyyyyyyyyyyyyyyyyyyhmd`    hNNNNNy:   ```-smmmy````NmmmNNNmmmmNNNNh/`  ```.+dhymNd+`    ``/hddd+```/NNNm-`` `mmssyyyyyyyyyyyyyyyyyyyyyyhyo/:----------------------:::\n" +
                "hhhhyyyhdmmmmmhssyyyyyyhhhdmmNmmddddddddddddddddddddddddmdddddmmmNmmmmhssssyhhhdddsssymmmmmmmdddmmdNNmmdssyyymmysdmmmmdssssshdhhhhhsssyhhmmdssssdmddddddddddddddddddddhhhdh+:---------------------::::::\n" +
                "hhhhhyyhdmmmNm/::/:::/+syydhhdmmy:------....------..---......--...-.--.....----.....-.....-....+ms:mh........--.....----....-...........`....``.```..................../yyss-------------------:::::::::\n" +
                "dhddhhhhdmNNNs:::-..----:oddhhhdmd+-...........................```...```............`````.....-dd..oN+.........................``````````````` ``````````````````````.smdyss+--------------::::///::::::\n" +
                "ddddddddmmNNd-:-.-.-:/+osyyyyyyyhddhyyhhhhhyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyyyyyyyyhyyyhhhhhhhhdm/..-hmhhhhhhhhhyyyhhhhhhyyyhyyyyyyyyyyhhhhhyyyyyyyyyyyyyyyyyyyyyyyyyhdNmmhyos------------:::::/+++//::::\n" +
                "ddhhdddmmmmm:..---/yhdmNNNNNNNNNmmmmmmmmmNNNmmNNNNNNNNNNNNNNNNNNNNNNNNNNNdhyhhhdddmmmNNNms/:::::-----:::::ohNdddydNmmmmmdmmmmmmdmmmNNNNNNmNNNNNNNNNNmmmmmmNNNNNNNmdmmmmmNNyss:-----------::::/+oso+//:::\n" +
                "ddddddddddd/---:::yNNNNNNNmmmNNNNNNNNMMNNmmdddmmmmNNNNNNMNNNNNMNNNMNNNNNmmhhhhhhdmmddNNNNNmy/-...--....:odmdhhhysdhhhyyhyhddmmNmmNmdhhyyhdNNNmmmmmddmmmmNNNNNNNNNNdddmdmNNhyso-------------::/osssso/:::\n" +
                "dddddddddd+.-:/++/dNNNNmddmmmmNNNNNNNNMMMMMNNNmmmmNNNNNNNNNNNMNNNMMNNNNyhmddddmmmmdhydhmNNNmmd-...----shyo++yhsssssoosyyyyyyydNNmmhhhddmNNNNNmmmmddmNNNNmNNNNNNNNNNmdmmdmNmyys+---:--------::+osyyso+/::\n" +
                "dddddddddy-/oyhddhNmmdhhhhddddddddmddhddmmNNNNMNNNNNNNNNNNNNNNNNMMMNNNdhNmmmmmmNNNmdhddmMMNNNy-..---.-/o:./ssyossyyhhhdmmmmmmmNNNmmNNNNMMMMNNNmmdmNNNmmmmmmmNNNNNNNmddmmmNNmyss:-:::::::::::/ossyyyo+:::\n" +
                "dddddddddyohmNmmNmmdysyddysssssyso+++++++oosydmNNmmNNNNMNMNNNNNNNNNNNNhhNmmNNNNNNMNddmhdMMNNm:./shds/--+/:-oyhhhddmmNNNNNNNNNNNNmmNNNNNMMMMNNmmmmmmmddddmmdddmNNNNNNNdddmmNNmyo::::::::::::/+osssyso/:::\n" +
                "dddddddddddmNdmNmmdhyhhysosysyy+//////////++++ossyhhhhhhyyyssoooossyyyyhhhhddddhhyyooo+ssydmy+hmmddmmds+mmmmNNNNNNNNNNNNNNNNmNNNNmNNNNNNMMMNNmmmmddddddmdmddddmNmmmNNNNddddmmdo::::::::::::/+ssssso+/:::\n" +
                "hddmddddhddmdmNdmdhmhhsooyhydy++++////////://///:::::::::////:::::::::::::::::::-------:::/shmmmyosNNdmmmNNNNNNNNNNNNNNNNNNmdmNNmmmmNNNNNNMNNNmmdddhhddddddhhhhdmmmmmNNNmmmdho::::::::::::/+osssso+/::::\n" +
                "yhdmmmdddddmmNdmddNmhddhhhhdh+++++//////::::::::::::::::::::::::::::::::-----------:::/+oo+//oymdo+ddyyhhhhhhddmmNNNmmmmmmmddhmNNmmNNNNNNmNNNNNNmmmddddhhhhddhhhhdmmmNNNNNms/:::::::::::::/+ssssso/:::::\n" +
                "osyhdmmmdddmNdmdhmmmhdmmmmNmso+//////////////////////////::/::::::://::::------:/+oo++++syo+/:+hysssso++++ooooooosydNmmmdhhhhhhmNmNNNNNNmyhNNNNNmmmNNNmmddddmdhhhhdmmNNNmdho:::::::::::::/+osssss+/:::::\n" +
                "+oosyhhddddNddmhhdNmhmmNNNNdyssooooooooooooo+++ooo+++++++++/////////::::----:///+shhhyo++yyo//:smmdhhhyysssoooooooooshdddhhhhhhhdmmmmmdddhdmNNNNmmmNmmdmmmmmddddddmmmmmdhhyy/::::::::::::/+osssso+/:::::\n" +
                "++++oosyyyhdyddhdmmmdmmmNNNhhyyyyyyyyyyyyysyyyysyyyyssssooo++o+++++//:::---:+ssssoyddhys++oso+//smMMNNNNmmdhhhhyyyyyyso+hhdddddmdhdddmdhyysyhmNNmmmddddddddhyhhdddmmmmmdhmdy/:::::::::::/+ossssso+/:::::\n" +
                "/////+++ooshydddNmmmdmNNNNmhhhhhhhhhhhhhhhhhhddddddddhhhhhhhhhyysso:-:::////+oyyhysoyhhyso+oyso+oyNMMMMMMMNNNmdddhhhhhhoyhdmNmNNmmhhhhhsooo+oshdddddmmNNNNmdmNNNNNNNmmdhhs+/::::::::::::/+ossssso+//////\n" +
                "////////+++yhdddNdmmdmNNNNNdhdddhdddddddddmmmmmmmmmmmmNmmmmmmmmmmho/://+syss++osyyyso+shysssshhyhmNMMMMMMMMMMMNNmmmdmdddydNNNhdNNNmyssoossyhdddddmNNNNNNNddmmmdddddhhhhhho:::::::::::::/+osssssso//:////\n" +
                "////////+//ohdhdmdmNNmNNNNNNmdmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNdsssosyyyyo+//oyyyssooyhyyyymNNMMMMMMMMMMMMMMMNNNNmmmmmNMMMNNNNNNdsyyhhdmNNNNNNMNNNNmdddddmddhhhhhhhdddy//:::::::::::/+ossssso+//://:/\n" +
                "////////////odddmmmNNNmNNNNNNNNNmmddhyysosshmNNNNNNNNNNNNMNMMNNNmNNNmmmmNNmdsoo+//oyyyssodmddmMMMMMMMMMMMMMMMMMMMMNNNNNNNNNMMNmmNNNdyhhyyhdmmmmNNNNNmmmddmmdddhhhhhhhddddhyhs/:::::::::/+sssssso+/::::::\n" +
                "/////////////sddmmmmNNNmmmmdhysoo+++++//////+sdNNNNNNNMNNNNNNNNNNNMNmdhdmNMMmhysooooyhdhmNMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNhyddhyhhyssyyddddmNNNmmmmmmddddmmmmNmNNNNNmmmhyyo::::::::/+osssssso+/::::::\n" +
                "++/+//////////sdmmmdhhysssyyyyso+////////////:/sdNNNNNNNNNNNNNNNNMNhsssssyhmmNmdmmddyydNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNdmMMs/mNNmmmmhhydmNNNNNNNNNNNNNMNNNNNmmmmmNNNNdy/::::::::/+ossssss+/:::::::\n" +
                "+/++///+/++/////ossssyyyyyyysssss+////////////::+ymNNNNNNNNNNNNNMmhs+/////+osyhdmNNNmmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNmMMd+NNNNNmmdhdmmNNNNNMMMMNNNmmmdddddddmmmdds/::::::::::/osssssso+/:::::::\n" +
                "++++++///:--../osoooooooooossssssso/::::::::::::::odNNNNNNNNNMNNNhhhyyhhhyysssssyydNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmNMmymmNNNmmdddmNMMMMMMNNNmmmmdmddddddddmmmh+::::::::::/+osssssso+/:::::::\n" +
                "+//::-.....``````:////+/+++///::----/-----:-----:--/hmNNNNNMMMNNNNsmdyhmmmmdhhyyyyyyhmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmmdyoNNNNmmdmNNMMMMMMNmNNmmmdddddddddddmdddd/-------::/+ssssssso/::::::::\n" +
                "-.....``````````````................-/:-------------:yNNNNNNNNNNN++s+-+dddNNmddddhhhhhmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNmNNMNNmmNNNMMMMMNNNmmmmmmmdddddhhhhmmdd+---------:/osssssso+/::::::::";
    }

}
